### ISSUE TITLE
Support wide-screens screen full width

### ISSUE THREAD

**Issue by manreo** [apotdevin/thunderhub#85] opened 2020-07-11 06:49 UTC
**Is your feature request related to a problem? Please describe.**
Hi, ThunderHub does not span the full width of the screen:
![image](https://user-images.githubusercontent.com/35897350/87218182-10d32480-c359-11ea-8538-4e9f2b054aea.png)
As you can see in the image, I have a wide screen, but it is not used. the information could be more spread if the screen is used, see for example how much more information I can see in a single page with RTL:
![image](https://user-images.githubusercontent.com/35897350/87218476-b5566600-c35b-11ea-9721-d1b1b395d126.png)

For example, there is so much information that can be shown in the channel menu if you use the full width of the scrren:
![image](https://user-images.githubusercontent.com/35897350/87218273-db7b0680-c359-11ea-9ad6-75f9d317aca4.png)

Thank you

**Comment by apotdevin** [comment] 2020-07-11 17:51
That is a very large screen! will think about it but this is by design so don't know if I would change it

**Comment by MrManPew** [comment] 2020-07-12 07:06
I understand the love to 80 char ;-)
But I assume the best design will be to add columns the lager the screen is.

Just one relevant point, whatever you decide, I do think that each forward should be not more than one line. So that one can see many forwards and compare. 
Also the columns headers (if you plan to add them) should be click-sorted..

Thanks

**Comment by apotdevin** [comment] 2022-01-20 11:24
Starting to change the UI and some of these ideas are going in! Closing this request for now

**Closed by apotdevin** 2022-01-20 11:24 UTC
