### ISSUE TITLE
LN Service bandwidth exhausted error?

### ISSUE THREAD

**Issue by andrerfneves** [apotdevin/thunderhub#227] opened 2021-03-16 17:27 UTC
**Describe the problem/bug**
Installed Thunderhub on a new node, following the same approach as previous setups. No hiccups on installation/running/logging in. Issue is found when I log into the Thunderhub UI and I see a lot of loading screens, and then it kicks me out of the session.

**Your environment**
* Version of ThunderHub: Latest `master` branch
* Deployment method: NPM?
* Other relevant environment details: Node 14.15

**Expected behavior**
Should have been able to fetch latest data from the node (channels/peers/etc)

**Actual behavior**
It `loads` on the UI for a few seconds (I thought it was fetching the data) and then it errors out and kicks me out of the session and outputs LOTS of the logs above.

**Screenshots/Links**
<img width="1530" alt="Screen Shot 2021-03-16 at 1 21 11 PM" src="https://user-images.githubusercontent.com/2574011/111352794-f45f5880-865a-11eb-989a-ff1c84d711d4.png">

Not sure where to begin debugging. LND is reachable, certs/macarroons are ok, accounts.yaml are ok. Any clues on where to focus debugging efforts?

Thanks in advance!

**Comment by apotdevin** [comment] 2021-03-16 19:47
Hey! What version of lnd are you running? And is it a node with a lot of channels/invoices/payments?

**Comment by andrerfneves** [comment] 2021-03-16 20:00
Lots of channels/invoices/payments. v0.12.1 LND Beta.

**Comment by apotdevin** [comment] 2021-03-16 20:05
This might be the reason then. Upon getting to the homepage ThunderHub requests a ton of information to populate the whole view. The problem is that it does all of them at the same time. Might need to progressively load the homepage to avoid this issue

**Comment by dlaptev** [comment] 2021-03-22 09:47
Hi Anthony, just jumping on this one since I am facing exactly the same issue, also a node with lots of channels. Would be curious if there is a workaround for the moment?

**Comment by apotdevin** [comment] 2021-03-22 14:04
Hey, also on the homepage view?

**Comment by dlaptev** [comment] 2021-03-22 14:42
Yes. SSO-authorized, I see the homepage, the on-/off-chain balance and payments, while routing info is loading. And then it crashes, logs me out and the backend spits a ton of “unable to get channel” and “unable to get node” errors.

**Comment by apotdevin** [comment] 2021-03-23 17:10
Will look into this

**Comment by apotdevin** [comment] 2021-03-23 19:47
I believe the exhausted bandwidth was coming from the forwards query where for each forwarded payment it was querying for the incoming and outgoing channel and channel peers data.

Refactored it so that it asks for much less data. Changes are now available in version v0.12.10.

Let me know if it helped!

**Comment by dlaptev** [comment] 2021-03-23 21:03
Oh man you are super fast! Happy to confirm that v0.12.10 fixes the issue for me (I indeed had lots of forwards)! Thanks a ton!

**Comment by apotdevin** [comment] 2021-03-23 21:11
No problem! Glad it helped

**Comment by apotdevin** [comment] 2021-05-02 15:28
Closing, let me know if the problem comes again!

**Closed by apotdevin** 2021-05-02 15:28 UTC
Labels: bug

**Comment by darthginger** [comment] 2021-10-13 06:59
Hi, just tried to switch from rtl to thunderhub and after login  i see "Transactions" loading and never completing because i get logged out. (probably because i have 10k+ payments and thunderhub wants to load them all?). I see alot of "Bandwidth exhausted" in the logs but also some other error( INTERNAL: Received RST_STREAM with code 2 (Internal server error)
thunderhub (latest master, says 0.12.30 on the home page)
node 14.18.0
These are just a few , but most of them just repeat:

error [THUB]: [
  503,
  'GetChainBalanceError',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]

error [THUB]: [
  503,
  'UnexpectedErrorWhenGettingChainBalance',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]

error [THUB]: [
  503,
  'UnexpectedErrorWhenGettingChainBalance',
  {
    err: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '8 RESOURCE_EXHAUSTED: Bandwidth exhausted',
      code: 8,
      details: 'Bandwidth exhausted',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]

error [THUB]: [
  503,
  'GetChainBalanceError',
  {
    err: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '8 RESOURCE_EXHAUSTED: Bandwidth exhausted',
      code: 8,
      details: 'Bandwidth exhausted',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]


error [THUB]: [
  503,
  'UnexpectedGetChannelsError',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]


error [THUB]: [
  503,
  'UnexpectedPendingChannelsErr',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:179:52)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /home/bitcoin/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:77:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]
