### ISSUE TITLE
broken after update to 0.13.2

### ISSUE THREAD

**Issue by MiBy0815** [apotdevin/thunderhub#395] opened 2022-01-30 16:33 UTC
Update went through but on "npm run start" I get this:

> thunderhub@0.13.2 start
> cross-env NODE_ENV=production nest start

node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn nest ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:475:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn nest',
  path: 'nest',
  spawnargs: [ 'start' ]
}

Node.js v17.0.1

**Comment by aphex3k** [comment] 2022-01-30 18:22
Duplicate of #393

**Comment by MiBy0815** [comment] 2022-02-01 07:49
sorry, missed that. Will close this

**Closed** 2022-02-01 07:49 UTC

**Comment by aphex3k** [comment] 2022-02-01 17:00
> sorry, missed that. Will close this

No problem :)
