### ISSUE TITLE
0.9.2: can't login with SSO

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#120] opened 2020-08-10 08:21 UTC
**Describe the problem/bug**
I'm unable to login with SSO - after entering the token (`https://example.com/thunderhub-rt?token=...`) I get "To start you must create an account on your server. You can find instructions for this here." page. There's a single log line:

```
2020-08-10 09:58:05 warn [THUB]: No SSO account available
```

Besides the message "Did you already create accounts?" looks like it should be clickable (the arrow on the right), but clicking it does nothing.

The JS console says: `Failed to load resource: the server responded with a status of 404 ()`
With this URL: https://example.com/_next/static/chunks/main-aa7e8ffb752d50036f4f.js

As you can see base_path is missing in the resource URL, so there's probably still something wrong with next. Not sure if it's related to inability to use SSO.

**Your environment**
* Version of ThunderHub: 0.9.2
* Deployment method: Debian package
* Other relevant environment details: Chromium 83.0.4103.116 (Developer Build)

**To Reproduce**
1. Configure ThunderHub with base path and SSO (example config below)
2. Launch Thunderhub
3. Open `https://example.com/thunderhub-rt/?token=...`

**Expected behavior**
The SSO account shows up

**Actual behavior**
Error page shows up

**Additional context**
<details>
<summary>ThunderHub config</summary>

```
BIND_PORT=4002

BITCOIN_NETWORK=regtest

COOKIE_PATH=/var/run/thunderhub-system-regtest/sso/cookie

DISABLE_LINKS=true

FETCH_FEES=false

FETCH_PRICES=false

NO_CLIENT_ACCOUNTS=true

NO_VERSION_CHECK=true

SSO_CERT_PATH=/var/lib/lnd-system-regtest/public/tls.cert

SSO_MACAROON_PATH=/var/lib/lnd-system-regtest/private

SSO_SERVER_URL=127.0.0.1:10011

BASE_PATH=/thunderhub-rt
```

</details>

<details>
<summary>Nginx config</summary>

```
location /thunderhub-rt {
	rewrite ^/thunderhub-rt$ / break;
        rewrite ^/thunderhub-rt(.*)$ $1 break;
	proxy_pass http://127.0.0.1:4002;
	proxy_http_version 1.1;
	proxy_set_header Host $http_host;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
}
```

</details>

**Comment by apotdevin** [comment] 2020-08-10 22:54
Checked and I can reproduce this problem. I not sure what is happening here but it's definitely related with the nextjs update. I will ask around in the nextjs repo but for the mean time looks like I need to revert this version update 👎

**Comment by apotdevin** [comment] 2020-08-12 08:05
Found the issue, was not with the version but an asset prefix config. Should be fixed now with version 0.9.3

**Closed by apotdevin** 2020-08-12 08:05 UTC

**Comment by Kixunil** [comment] 2020-08-12 14:55
Hmm, did you sign it? I'm getting verification error.

**Comment by apotdevin** [comment] 2020-08-12 15:17
I did, I see the tag and the release with the verified tag as well. Only change with this release is I tried a release drafter, maybe it didn't do the correct signature? Still weird that it appears as verified on github

**Comment by Kixunil** [comment] 2020-08-12 15:31
Ah, I see now, you signed the commit, not the tag. Did you do it intentionally? I can verify commits too, would like to know if you plan to continue signing commits only or if this was temporary/unintentional.

**Comment by apotdevin** [comment] 2020-08-16 16:21
Hey! Ah, I understand now. The release-drafter uses the commit signature to verify. Yeah, better to verify commits that way I can continue using this release-drafter without the need of signing the tag directly :)
