### ISSUE TITLE
ThunderHub is making too many RPC connections to LND

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#178] opened 2020-12-03 08:20 UTC
**Describe the problem/bug**
After updating ThunderHub to the latest version, I found out that after a while LND reported too many open files. Based on the fact that I upgraded ThunderHub, I checked how many file descriptors *ThunderHub* has opened and found it's more than a thousand. LND had full 1024 file descriptors open. After stopping ThunderHub, the file descriptors of LND went down to two digit numbers.

**Your environment**
* Version of ThunderHub: 0.10.5 (latest)
* Deployment method: Debian package
* Other relevant environment details: LND 0.11.1 (latest); SSO enabled in ThunderHub

**To Reproduce**
1. Upgrade ThunderHub
2. Open it and play a while
3. Wait a while
4. Attempt to use it again
5. If it doesn't work, check FD counts: `sudo ls /proc/`ps aux | grep lnd | grep -v grep | awk '{print $2}'`/fd | wc -l`; `sudo ls /proc/`ps aux | grep thunderhub | grep -v grep | awk '{print $2}'`/fd | wc -l`
5. Stop ThunderHub after reaching the limit
6. Check the FD counts again.

**Expected behavior**
ThunderHub can be used indefinitely without opening more file descriptors than absolutely required.

**Actual behavior**
ThunderHub opens too many connections to LND

**Comment by apotdevin** [comment] 2020-12-03 21:20
Need to look into this. Also think this is a duplicate of https://github.com/apotdevin/thunderhub/issues/172 :) Will close this one in favor of the other

**Closed by apotdevin** 2020-12-03 21:20 UTC

**Comment by Kixunil** [comment] 2020-12-03 22:19
Damn, got confused during bug reporting which caused me to forget to check existing issues. Sorry about that and thanks for info!

**Comment by apotdevin** [comment] 2020-12-03 22:26
No problem :) Should be fixed now for the next release 👍
